admin_index:
    path: /
    defaults: { _controller: NfqAdminBundle:Dashboard:index }

admin_login:
    path: /login
    defaults: { _controller: NfqAdminBundle:Authentication:login }

admin_logout:
    path: /logout
    defaults: { _controller: NfqAdminBundle:Authentication:logout }

admin_security_check:
    path: /login/check
    defaults: { _controller: NfqAdminBundle:Authentication:securityCheck }


nfq_admin_locale_widget:
    path: /adminwidget/locale
    defaults: { _controller: NfqAdminBundle:Locale:index }